name: flight-search-services
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/pg

    ports:
      - 5432:5432

volumes:
  pg_data:
    driver: bridge
